
%
% NOTE -- ONLY EDIT THE .Rnw FILE!!!  The .tex file is
% likely to be overwritten.
%
\documentclass[12pt]{article}

\usepackage{amsmath,pstricks}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}


\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}


\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rfunarg}[1]{{\texttt{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}

\textwidth=6.2in

\bibliographystyle{plainnat} 
 
\begin{document}
%\setkeys{Gin}{width=0.55\textwidth}


The interchange between Baggerly, Coombes and Neeley (BCN) and
Dressman, Potti and Nevins (DPN) in XXX is of broad interest
to cancer bioinformaticians.  We are indebted to Dressman and
colleagues for voluntarily making available much of the
data and analytic resources underlying the ``Integrated
genomic-based approach'' paper of 2007.  We are indebted to
Baggerly and colleagues for their meticulous approach to
re-assessing the paper in conjunction with the data.  

To review, BCN use the archive at \url{http://data.cgt.duke.edu/platinum.php}
along with the GEO submission of Bild et al. (XXX, GSE3156) to raise
a number of concerns regarding the main paper on targeting treatment
of ovarian cancer.  I select those that are
simplest to illustrate and interpret.

\textbf{First}, the ``corrected RMA'' expression quantifications

\url{https://discovery.genome.duke.edu/express/resources/193/correctedplatinum_RMA.xls}, 

retrieved online May 8 2009, appear to have \textbf{mislabeled columns}.

This was apparently discovered through an attempt to understand
the difference between RMA preprocessed arrays, readily generated
using the  CEL files in

\url{https://discovery.genome.duke.edu/express/resources/1144/PlatinumJCO.zip},

and the ``corrected RMA'' data, which consists of RMA quantifications
that are additionally processed by ``sparse factor regression''
to remove artifacts.

Figure 1 shows how the mislabeling can be discovered and corrected;
full details are provided in the original supplements of BCN's
letter, but using a Bioconductor experimental data package,
\textit{dressCheck}, we can illustrate the problem readily.

<<ged,keep.source=TRUE>>=
library(dressCheck)
if (!exists("c119")) data(c119) # pure RMA on CEL files, with trimming of sample names
if (!exists("DrAsGiven")) data(DrAsGiven) # read of corrected platinum XLS to CSV
    # some names are not preserved between two images
setdiff(sampleNames(c119), sampleNames(DrAsGiven))
    # use the common ones
okn = intersect(sampleNames(DrAsGiven), sampleNames(c119))
    # the corrected XLS does not have all genes, so c119 needs trim
c119r = c119[ featureNames(DrAsGiven), ]
    # now demonstrate
allc1 = sapply(okn, function(i) cor(exprs(DrAsGiven)[,okn[1]],
   exprs(c119r[,i])))
png(file="corChk.png")
par(mfrow=c(2,2))
remap1 = which.max(allc1)
plot(exprs(DrAsGiven)[,okn[1]], exprs(c119r)[,okn[1]],
 xlab=paste("id", okn[1], "in RMA+SFR XLS"),
 ylab=paste("id", okn[1], "in pure RMA from CEL"),
 main="(a)")
plot(exprs(DrAsGiven)[,okn[1]], exprs(c119r)[,names(remap1)],
 xlab=paste("id", okn[1], "in RMA+SFR XLS"),
 ylab=paste("id", names(remap1), "in pure RMA from CEL"),
 main="(b)")
allc2 = sapply(okn, function(i) cor(exprs(DrAsGiven)[,okn[2]],
   exprs(c119r[,i])))
remap2 = which.max(allc2)
plot(exprs(DrAsGiven)[,okn[2]], exprs(c119r)[,okn[2]],
 xlab=paste("id", okn[2], "in RMA+SFR XLS"),
 ylab=paste("id", okn[2], "in pure RMA from CEL"),
 main="(c)")
plot(exprs(DrAsGiven)[,okn[2]], exprs(c119r)[,names(remap2)],
 xlab=paste("id", okn[2], "in RMA+SFR XLS"),
 ylab=paste("id", names(remap2), "in pure RMA from CEL"),
 main="(d)")
dev.off()
@

\includegraphics{corChk}

Panels (a) and (c) show the kind of relationship expected when
two arrays on different samples are compared.  Panels
(b) and (d) shows the kind of relationship expected when slightly
different preprocessing method are applied to the same
sample.  BCN did this exercise very systematically,
concluding that the 'corrected RMA' arrays 1024 and 1447
in the XLS
matche the CEL files (and thus the clinical data
series for) 2505 and 1578 respectively.  In their response, DPN acknowledge
the identifier scrambling and remark that mislabeling only
affected the publication of data on the web site, not
the analyses underlying the paper.

\end{document}
